ignore:
  - vulnerability: CVE-2026-11822
    package:
      name: libsqlite3-0
      type: deb
  - vulnerability: CVE-2026-11824
    package:
      name: libsqlite3-0
      type: deb
  - vulnerability: CVE-2026-41992
    package:
      name: gzip
      type: deb
  - vulnerability: CVE-2026-54369
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-54370
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-58469
    package:
      name: wget
      type: deb

  # --- added by curator on 2026-08-07 (UTC) ---
  # High — upstream won't-fix
  - vulnerability: CVE-2026-58471
    package:
      name: wget
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-58472
    package:
      name: wget
      type: deb
  # Critical — upstream won't-fix
  - vulnerability: CVE-2026-6653
    package:
      name: libxml2
      type: deb
