ignore:
  - vulnerability: CVE-2026-11822
    package:
      name: libsqlite3-0
      type: deb
  - vulnerability: CVE-2026-11824
    package:
      name: libsqlite3-0
      type: deb
  - vulnerability: CVE-2026-12087
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-13221
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-41992
    package:
      name: gzip
      type: deb
  - vulnerability: CVE-2026-48959
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-48961
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-48962
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-54369
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-54370
    package:
      name: libacl1
      type: deb
  - vulnerability: CVE-2026-57432
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-57433
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-58469
    package:
      name: wget
      type: deb
  - vulnerability: CVE-2026-7017
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-58471
    package:
      name: wget
      type: deb
  - vulnerability: CVE-2026-58472
    package:
      name: wget
      type: deb
  - vulnerability: CVE-2026-6653
    package:
      name: libxml2
      type: deb
  - vulnerability: CVE-2025-69720
    package:
      name: libncursesw6
      type: deb
  - vulnerability: CVE-2025-69720
    package:
      name: libtinfo6
      type: deb
  - vulnerability: CVE-2025-69720
    package:
      name: ncurses-base
      type: deb
  - vulnerability: CVE-2025-69720
    package:
      name: ncurses-bin
      type: deb
  - vulnerability: CVE-2026-42496
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-42497
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-5435
    package:
      name: libc-bin
      type: deb
  - vulnerability: CVE-2026-5435
    package:
      name: libc6
      type: deb
  - vulnerability: CVE-2026-5450
    package:
      name: libc-bin
      type: deb
  - vulnerability: CVE-2026-5450
    package:
      name: libc6
      type: deb
  - vulnerability: CVE-2026-5928
    package:
      name: libc-bin
      type: deb
  - vulnerability: CVE-2026-5928
    package:
      name: libc6
      type: deb
  - vulnerability: CVE-2026-8376
    package:
      name: perl-base
      type: deb
  - vulnerability: CVE-2026-9538
    package:
      name: perl-base
      type: deb

  # --- added by curator on 2026-09-05 (UTC) ---
  # High — upstream won't-fix
  - vulnerability: CVE-2026-76642
    package:
      name: bsdutils
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-76642
    package:
      name: libblkid1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-76642
    package:
      name: liblastlog2-2
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-76642
    package:
      name: libmount1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-76642
    package:
      name: libsmartcols1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-76642
    package:
      name: libuuid1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-76642
    package:
      name: login
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-76642
    package:
      name: mount
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-76642
    package:
      name: util-linux
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78408
    package:
      name: bsdutils
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78408
    package:
      name: libblkid1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78408
    package:
      name: liblastlog2-2
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78408
    package:
      name: libmount1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78408
    package:
      name: libsmartcols1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78408
    package:
      name: libuuid1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78408
    package:
      name: login
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78408
    package:
      name: mount
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78408
    package:
      name: util-linux
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78409
    package:
      name: bsdutils
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78409
    package:
      name: libblkid1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78409
    package:
      name: liblastlog2-2
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78409
    package:
      name: libmount1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78409
    package:
      name: libsmartcols1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78409
    package:
      name: libuuid1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78409
    package:
      name: login
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78409
    package:
      name: mount
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78409
    package:
      name: util-linux
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78410
    package:
      name: bsdutils
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78410
    package:
      name: libblkid1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78410
    package:
      name: liblastlog2-2
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78410
    package:
      name: libmount1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78410
    package:
      name: libsmartcols1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78410
    package:
      name: libuuid1
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78410
    package:
      name: login
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78410
    package:
      name: mount
      type: deb
  # High — upstream won't-fix
  - vulnerability: CVE-2026-78410
    package:
      name: util-linux
      type: deb
